// Minimal bilingual UI strings — the kitchens are bilingual per the design
// handoff, so this is scoped in from the start rather than bolted on later.
// Log/unit/item names come from the database (kitchen-authored, English) and
// aren't translated here; this covers app chrome only.

export type Lang = "en" | "es";

export const strings = {
  en: {
    change: "Change",
    ofDoneToday: (done: number, total: number) => `of ${total} done today`,
    todo: "TO DO",
    done: "DONE",
    today: "Today",
    records: "Records",
    certificates: "CERTIFICATES",
    pastMonths: "PAST MONTHS",
    allFine: "All fine",
    outOfRange: "Out of range",
    nothingYet: "Nothing yet",
    nothingRecorded: "Nothing written down for this day yet.",
    writtenDownBy: (name: string) => `Written down by ${name}`,
    chooseKitchen: "CHOOSE YOUR KITCHEN",
    back: "Back",
    tapAndType: "Tap a box and type the number",
    tickEach: "Tick each one as you finish it",
    whatDidYouDo: "What did you do about it?",
    submit: "Done — sign my name",
    fillEveryBox: "Fill in every box first",
    pickWhatYouDid: "Pick what you did about the reading above",
    ticked: (n: number, total: number) => `${n} of ${total} ticked`,
    signsAs: (name: string, site: string) => `Signs as ${name} · ${site}`,
    cancel: "Cancel",
    save: "Save",
    signIn: "Sign in",
    enterPin: "Enter your PIN",
    wrongPin: "Wrong PIN — try again",
    savedAndSigned: (name: string) => `${name} saved and signed.`,
    savedOffline: (name: string) => `${name} saved — will sync when back online.`,
    syncing: "Syncing…",
    offline: "Offline",
    signOut: "Sign out",
    exportData: "EXPORT DATA",
    exportCsv: "Download CSV",
    exportPdf: "Download PDF",
    exportThisMonth: (name: string) => `${name}, this month`,
  },
  es: {
    change: "Cambiar",
    ofDoneToday: (done: number, total: number) => `de ${total} hechos hoy`,
    todo: "PENDIENTE",
    done: "HECHO",
    today: "Hoy",
    records: "Registros",
    certificates: "CERTIFICADOS",
    pastMonths: "MESES ANTERIORES",
    allFine: "Todo bien",
    outOfRange: "Fuera de rango",
    nothingYet: "Nada aún",
    nothingRecorded: "No se ha registrado nada este día todavía.",
    writtenDownBy: (name: string) => `Anotado por ${name}`,
    chooseKitchen: "ELIGE TU COCINA",
    back: "Atrás",
    tapAndType: "Toca una casilla y escribe el número",
    tickEach: "Marca cada uno al terminarlo",
    whatDidYouDo: "¿Qué hiciste al respecto?",
    submit: "Listo — firmar",
    fillEveryBox: "Completa todas las casillas primero",
    pickWhatYouDid: "Elige qué hiciste con la lectura de arriba",
    ticked: (n: number, total: number) => `${n} de ${total} marcados`,
    signsAs: (name: string, site: string) => `Firma como ${name} · ${site}`,
    cancel: "Cancelar",
    save: "Guardar",
    signIn: "Iniciar sesión",
    enterPin: "Ingresa tu PIN",
    wrongPin: "PIN incorrecto — intenta de nuevo",
    savedAndSigned: (name: string) => `${name} guardado y firmado.`,
    savedOffline: (name: string) => `${name} guardado — se sincronizará al volver la conexión.`,
    syncing: "Sincronizando…",
    offline: "Sin conexión",
    signOut: "Cerrar sesión",
    exportData: "EXPORTAR DATOS",
    exportCsv: "Descargar CSV",
    exportPdf: "Descargar PDF",
    exportThisMonth: (name: string) => `${name}, este mes`,
  },
};

export function useStringsFor(lang: Lang) {
  return strings[lang];
}
