// Minimal bilingual UI strings — the kitchens are bilingual per the design
// handoff, so this is scoped in from the start rather than bolted on later.
// Log/unit/item names come from the database (kitchen-authored, English) and
// aren't translated here; this covers app chrome only.

export type Lang = "en" | "es";

export const strings = {
  en: {
    change: "Change",
    ofDoneToday: (done: number, total: number) => `of ${total} done today`,
    todo: "TO DO",
    done: "DONE",
    today: "Today",
    records: "Records",
    certificates: "CERTIFICATES",
    pastMonths: "PAST MONTHS",
    allFine: "All fine",
    outOfRange: "Out of range",
    nothingYet: "Nothing yet",
    nothingRecorded: "Nothing written down for this day yet.",
    writtenDownBy: (name: string) => `Written down by ${name}`,
    chooseKitchen: "CHOOSE YOUR KITCHEN",
    back: "Back",
    tapAndType: "Tap a box and type the number",
    tickEach: "Tick each one as you finish it",
    whatDidYouDo: "What did you do about it?",
    submit: "Done — sign my name",
    fillEveryBox: "Fill in every box first",
    pickWhatYouDid: "Pick what you did about the reading above",
    ticked: (n: number, total: number) => `${n} of ${total} ticked`,
    signsAs: (name: string, site: string) => `Signs as ${name} · ${site}`,
    cancel: "Cancel",
    save: "Save",
    signIn: "Sign in",
    enterPin: "Enter your PIN",
    wrongPin: "Wrong PIN — try again",
    savedAndSigned: (name: string) => `${name} saved and signed.`,
    savedOffline: (name: string) => `${name} saved — will sync when back online.`,
    syncing: "Syncing…",
    offline: "Offline",
    signOut: "Sign out",
    exportData: "EXPORT DATA",
    exportCsv: "Download CSV",
    exportPdf: "Download PDF",
    exportThisMonth: (name: string) => `${name}, this month`,
    thermometerId: "Thermometer ID",
    referenceReading: "Reference reading",
    testReading: "Test reading",
    addThermometer: "+ Add thermometer",
    removeRow: "Remove",
    outOfTolerance: (tolerance: number) => `More than ${tolerance}° off reference`,
    calibrationComment: "What did you do about it?",
    fillEveryRow: "Fill in every field for each thermometer",
    addAtLeastOne: "Add at least one thermometer",
    invoiceNumber: "Invoice #",
    distributorName: "Distributor name",
    yes: "Yes",
    no: "No",
    wfcfoApproved: "Approved WFCFO supplier?",
    nonGmoApproved: "Approved Non-GMO supplier?",
    truckConditionGood: "Truck condition good?",
    truckTempCompliant: "Truck temperature compliant?",
    truckTempF: "Truck temperature (°F)",
    palletConditionGood: "Pallet condition good?",
    plasticWrapGood: "Plastic wrap condition good?",
    productsToStandard: "Product(s) to standard?",
    labelsCurrent: "Product labels current?",
    sealIntact: "Seal intact and matches the paperwork?",
    caseCountMatches: "Case count matches the invoice?",
    supplierPaperworkAttached: "Supplier paperwork attached?",
    organicCertCurrent: "Organic certificate still current?",
    explainWhy: "Explain why",
    products: "Products",
    addProduct: "+ Add product",
    productName: "Product name",
    productId: "Product ID",
    productCount: "Count",
    lotNumber: "Lot #",
    allergenProduct: "Allergen product?",
    labeledOrganic: "Labeled organic?",
    storage: "Storage",
    dry: "Dry",
    refrig: "Refrig",
    freezer: "Freezer",
    fillReceivingRequired: "Fill in every required field, and explain any \"No\" answers",
    signOffReview: "Sign off & review",
    needsReview: "Needs review",
    reviewed: "Reviewed",
    reviewedBy: (name: string) => `Reviewed by ${name}`,
    approve: "Approve",
    reject: "Reject",
    releasedForUse: "Released for use?",
    submitReview: "Submit review",
    managerSignIn: "Manager sign-in",
    backToKitchenSignIn: "Back to kitchen sign-in",
    noReceivingLogsThisMonth: "No receiving logs this month",
  },
  es: {
    change: "Cambiar",
    ofDoneToday: (done: number, total: number) => `de ${total} hechos hoy`,
    todo: "PENDIENTE",
    done: "HECHO",
    today: "Hoy",
    records: "Registros",
    certificates: "CERTIFICADOS",
    pastMonths: "MESES ANTERIORES",
    allFine: "Todo bien",
    outOfRange: "Fuera de rango",
    nothingYet: "Nada aún",
    nothingRecorded: "No se ha registrado nada este día todavía.",
    writtenDownBy: (name: string) => `Anotado por ${name}`,
    chooseKitchen: "ELIGE TU COCINA",
    back: "Atrás",
    tapAndType: "Toca una casilla y escribe el número",
    tickEach: "Marca cada uno al terminarlo",
    whatDidYouDo: "¿Qué hiciste al respecto?",
    submit: "Listo — firmar",
    fillEveryBox: "Completa todas las casillas primero",
    pickWhatYouDid: "Elige qué hiciste con la lectura de arriba",
    ticked: (n: number, total: number) => `${n} de ${total} marcados`,
    signsAs: (name: string, site: string) => `Firma como ${name} · ${site}`,
    cancel: "Cancelar",
    save: "Guardar",
    signIn: "Iniciar sesión",
    enterPin: "Ingresa tu PIN",
    wrongPin: "PIN incorrecto — intenta de nuevo",
    savedAndSigned: (name: string) => `${name} guardado y firmado.`,
    savedOffline: (name: string) => `${name} guardado — se sincronizará al volver la conexión.`,
    syncing: "Sincronizando…",
    offline: "Sin conexión",
    signOut: "Cerrar sesión",
    exportData: "EXPORTAR DATOS",
    exportCsv: "Descargar CSV",
    exportPdf: "Descargar PDF",
    exportThisMonth: (name: string) => `${name}, este mes`,
    thermometerId: "ID del termómetro",
    referenceReading: "Lectura de referencia",
    testReading: "Lectura de prueba",
    addThermometer: "+ Añadir termómetro",
    removeRow: "Quitar",
    outOfTolerance: (tolerance: number) => `Más de ${tolerance}° de diferencia`,
    calibrationComment: "¿Qué hiciste al respecto?",
    fillEveryRow: "Completa todos los campos de cada termómetro",
    addAtLeastOne: "Añade al menos un termómetro",
    invoiceNumber: "Factura #",
    distributorName: "Nombre del distribuidor",
    yes: "Sí",
    no: "No",
    wfcfoApproved: "¿Proveedor WFCFO aprobado?",
    nonGmoApproved: "¿Proveedor Non-GMO aprobado?",
    truckConditionGood: "¿Condición del camión buena?",
    truckTempCompliant: "¿Temperatura del camión cumple?",
    truckTempF: "Temperatura del camión (°F)",
    palletConditionGood: "¿Condición del palet buena?",
    plasticWrapGood: "¿Envoltura de plástico buena?",
    productsToStandard: "¿Producto(s) a estándar?",
    labelsCurrent: "¿Etiquetas de productos actuales?",
    sealIntact: "¿Sello intacto y coincide con el papeleo?",
    caseCountMatches: "¿El conteo de cajas coincide con la factura?",
    supplierPaperworkAttached: "¿Papeleo del proveedor adjunto?",
    organicCertCurrent: "¿Certificado orgánico vigente?",
    explainWhy: "Explica por qué",
    products: "Productos",
    addProduct: "+ Añadir producto",
    productName: "Nombre del producto",
    productId: "ID del producto",
    productCount: "Cantidad",
    lotNumber: "Lote #",
    allergenProduct: "¿Producto alérgeno?",
    labeledOrganic: "¿Orgánico etiquetado?",
    storage: "Almacenamiento",
    dry: "Seco",
    refrig: "Refrigerado",
    freezer: "Congelado",
    fillReceivingRequired: "Completa todos los campos requeridos y explica cualquier respuesta \"No\"",
    signOffReview: "Firmar y revisar",
    needsReview: "Necesita revisión",
    reviewed: "Revisado",
    reviewedBy: (name: string) => `Revisado por ${name}`,
    approve: "Aprobar",
    reject: "Rechazar",
    releasedForUse: "¿Liberado para su uso?",
    submitReview: "Enviar revisión",
    managerSignIn: "Inicio de sesión de gerente",
    backToKitchenSignIn: "Volver al inicio de sesión de cocina",
    noReceivingLogsThisMonth: "Sin registros de recepción este mes",
  },
};

export function useStringsFor(lang: Lang) {
  return strings[lang];
}
